name: os-mac

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]
        test-suite: ['default']

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm install -g vue-cli

      - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: bash ./tests/init.sh
        env:
          CI: true
          TEST_SUITE: ${{ matrix.test-suite }}
